name: Update ISO

on: [push]

jobs:
  download-update:
    runs-on: ubuntu-latest

    steps:
    - name: Check and update ISO
      run: |
        [ -f CorePure64-14.0.iso ] || wget -O CorePure64-14.0.iso https://distro.ibiblio.org/tinycorelinux/14.x/x86_64/release/CorePure64-14.0.iso
        git add CorePure64-14.0.iso && git commit -m "Update ISO" || true
        git push

        remote_date=$(curl -sI https://distro.ibiblio.org/tinycorelinux/14.x/x86_64/release/CorePure64-14.0.iso | grep Last-Modified | cut -d' ' -f2-)
        local_date=$(stat -c %y CorePure64-14.0.iso)

        [[ $remote_date > $local_date ]] && echo "Remote ISO is newer. Updating..." && cp CorePure64-14.0.iso $GITHUB_WORKSPACE && git add CorePure64-14.0.iso && git commit -m "Update ISO" && git push || echo "Local ISO is up to date."
