name: Update repo

on: [push]

jobs:
  runscript:
    name: Run Updater Script
    runs-on: ubuntu-latest
    steps:
      - name: Call a Bash Script
        run:  bash ${GITHUB_WORKSPACE}/scripts/repo-updater.sh
