name: Update File List

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * *" # Runs the job everyday at 0:0 UTC

jobs:
  runscript:
    name: Run Updater Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Call a Bash Script
        run:  bash  ./scripts/repo-updater.sh
